### ISSUE TITLE
Program does not launch or exit properly on macOS

### ISSUE THREAD

**Issue by krs013** [Trilarion/imperialism-remake#32] opened 2017-08-01 20:12 UTC
This is a blanket issue to track my observations while I test on macOS. As I find specific problems, I may split them off into other issues, but for now I don't have enough information to treat them narrowly.

Running `start.py` on macOS does not get the game to run in a way that is usable yet. Problems include:
* Full screen problems
  * If launched from a normal terminal window (not full screen), the program enters full screen but then goes grey, like it needs an extra paint cycle or something. Mousing over the button areas reveals those graphics, but I can't get the original window to display more than a half second before it goes grey.
![screen shot 2017-08-01 at 2 10 41 pm](https://user-images.githubusercontent.com/3606458/28844850-3d09e8c6-76c3-11e7-9b79-996129e131e4.png)

  * If launched from a full screen terminal window, an error occurs (the `Network: cannot listen` error from #8) and the resulting window is scaled for full screen but drawn. 
![screen shot 2017-08-01 at 2 07 02 pm](https://user-images.githubusercontent.com/3606458/28844699-c59e25d6-76c2-11e7-832a-de5b5facf754.png)
* Does not exit: When I click on the door to quit the program, the window disappears, but the server and/or `start.py` does not exit, and I have to Ctrl+C three times to actually close the program.

All of these issues are macOS-specific and I cannot reproduce them in Ubuntu. (Although I don't have a real full screen mode in Ubuntu as it's configured, so that might not be completely true).

**Comment by krs013** [comment] 2017-08-01 20:13
Fixing these issues will be a prerequisite to packaging the app, for me at least. (#12)

**Comment by Trilarion** [comment] 2017-08-01 21:45
Unfortunately I cannot help there without a Mac computer available here. The easiest way to debug this is to throw things out until you arrive at a behavior that is more in line with expectations, then start to put things back in. It's mostly just the client/client.py and there the start screen.

The other approach is to make a demo PyQt5 application from the scratch and make it more and more like the client window. In any case, the used Python 3 and PyQt5 packages should be up to date.

The getting stuck on exiting is probably related to the waiting for the server process to join again, which probably doesn't shut down correctly (might be caused by the Network cannot listen error). Does the game exit okay if the server is disabled (do not run the server process, do not wait for it to finish)?

The gray area might be some funny effect of a widget not getting a resize event. Not sure there. Trying to boil it down to a minimal example showing the effect should help. Could as well even be a problem with PyQt5 for macOs.

Hope that helps.

**Comment by Trilarion** [comment] 2017-08-01 21:48
The Network cannot listen error also occured on Ubuntu, so I can test and try to eliminate it there. It might help with macOs.

The Qt stuff showing the start window is not as nice code as I would wish it to be. I can improve on it in the next days and you can improve it too if you want. However, I cannot test anything on a Mac and on Windows it looks as expected.

**Comment by krs013** [comment] 2017-08-03 06:06
Thanks, I think that will help a lot. I won't be able to get a start until next week, but I am looking forward to getting a bit more into the code this time!

**Comment by oaken-source** [comment] 2020-09-27 15:57
I have just tried the program on a mac, and, although the game is not playable for different reasons, I cannot reproduce the behaviour described in this report.

**Comment by Trilarion** [comment] 2020-09-28 07:58
Thanks for the observation. In the meantime a macOS developer committed code changes, so that likely fixed the issue. I will close it. If the problem persists, the issue can be reopened.

**Closed by Trilarion** 2020-09-28 07:58 UTC
Labels: bug
